# Generated by Django 4.2 on 2023-06-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='corredores',
        ),
    ]
