# Generated by Django 4.2 on 2023-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final', '0002_rename_estudiante_corredores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('kilometros', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
