# Generated by Django 4.2 on 2023-06-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final', '0003_carreras_delete_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
