# Generated by Django 4.2 on 2023-06-28 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_account_cuenta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='Account',
        ),
    ]
